package com.clesun.web.skyland.dao;

import com.clesun.web.skyland.entity.Equipment;
import com.clesun.web.skyland.entity.EquipmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    int countByExample(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    int deleteByExample(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    int insert(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    int insertSelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    List<Equipment> selectByExample(EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    Equipment selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") Equipment record, @Param("example") EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    int updateByExample(@Param("record") Equipment record, @Param("example") EquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    int updateByPrimaryKeySelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUIPMENT
     *
     * @mbggenerated Tue Jan 15 12:33:05 CST 2019
     */
    int updateByPrimaryKey(Equipment record);
}