package com.clesun.web.skyland.dao;

import com.clesun.web.skyland.entity.Farmwork;
import com.clesun.web.skyland.entity.FarmworkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FarmworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMWORK
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int countByExample(FarmworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMWORK
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int deleteByExample(FarmworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMWORK
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int insert(Farmwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMWORK
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int insertSelective(Farmwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMWORK
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    List<Farmwork> selectByExample(FarmworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMWORK
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Farmwork record, @Param("example") FarmworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMWORK
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int updateByExample(@Param("record") Farmwork record, @Param("example") FarmworkExample example);
}