package com.clesun.web.skyland.dao;

import com.clesun.web.skyland.entity.Farmresource;
import com.clesun.web.skyland.entity.FarmresourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FarmresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMRESOURCE
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int countByExample(FarmresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMRESOURCE
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int deleteByExample(FarmresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMRESOURCE
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int insert(Farmresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMRESOURCE
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int insertSelective(Farmresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMRESOURCE
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    List<Farmresource> selectByExample(FarmresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMRESOURCE
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Farmresource record, @Param("example") FarmresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FARMRESOURCE
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    int updateByExample(@Param("record") Farmresource record, @Param("example") FarmresourceExample example);
}