package com.clesun.web.skyland.dao;

import com.clesun.web.skyland.entity.Plantrecord;
import com.clesun.web.skyland.entity.PlantrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlantrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLANTRECORD
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    int countByExample(PlantrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLANTRECORD
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    int deleteByExample(PlantrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLANTRECORD
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    int insert(Plantrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLANTRECORD
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    int insertSelective(Plantrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLANTRECORD
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    List<Plantrecord> selectByExample(PlantrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLANTRECORD
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Plantrecord record, @Param("example") PlantrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLANTRECORD
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    int updateByExample(@Param("record") Plantrecord record, @Param("example") PlantrecordExample example);
}