package com.clesun.web.skyland.dao;

import com.clesun.web.skyland.entity.ZhnyNsgl;
import com.clesun.web.skyland.entity.ZhnyNsglExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhnyNsglMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int countByExample(ZhnyNsglExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int deleteByExample(ZhnyNsglExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int insert(ZhnyNsgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int insertSelective(ZhnyNsgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    List<ZhnyNsgl> selectByExample(ZhnyNsglExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    ZhnyNsgl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") ZhnyNsgl record, @Param("example") ZhnyNsglExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int updateByExample(@Param("record") ZhnyNsgl record, @Param("example") ZhnyNsglExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int updateByPrimaryKeySelective(ZhnyNsgl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSGL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int updateByPrimaryKey(ZhnyNsgl record);
}