package com.clesun.web.skyland.dao;

import com.clesun.web.skyland.entity.ZhnyNsxqTrp;
import com.clesun.web.skyland.entity.ZhnyNsxqTrpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhnyNsxqTrpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int countByExample(ZhnyNsxqTrpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int deleteByExample(ZhnyNsxqTrpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int insert(ZhnyNsxqTrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int insertSelective(ZhnyNsxqTrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    List<ZhnyNsxqTrp> selectByExample(ZhnyNsxqTrpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    ZhnyNsxqTrp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") ZhnyNsxqTrp record, @Param("example") ZhnyNsxqTrpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int updateByExample(@Param("record") ZhnyNsxqTrp record, @Param("example") ZhnyNsxqTrpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int updateByPrimaryKeySelective(ZhnyNsxqTrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    int updateByPrimaryKey(ZhnyNsxqTrp record);
}