package com.clesun.web.skyland.entity;

public class Farmwork {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMWORK.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMWORK.mc
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMWORK.czgf
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String czgf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMWORK.pic
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMWORK.bh
     *
     * @return the value of FARMWORK.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMWORK.bh
     *
     * @param bh the value for FARMWORK.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMWORK.mc
     *
     * @return the value of FARMWORK.mc
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMWORK.mc
     *
     * @param mc the value for FARMWORK.mc
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMWORK.czgf
     *
     * @return the value of FARMWORK.czgf
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getCzgf() {
        return czgf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMWORK.czgf
     *
     * @param czgf the value for FARMWORK.czgf
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setCzgf(String czgf) {
        this.czgf = czgf == null ? null : czgf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMWORK.pic
     *
     * @return the value of FARMWORK.pic
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMWORK.pic
     *
     * @param pic the value for FARMWORK.pic
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }
}