package com.clesun.web.skyland.entity;

import io.swagger.annotations.ApiModelProperty;

public class Farmresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMRESOURCE.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    @ApiModelProperty(value = "投入品编号")
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMRESOURCE.type
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    @ApiModelProperty(value = "投入品类型")
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMRESOURCE.mc
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    @ApiModelProperty(value = "投入品名称")
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMRESOURCE.sccs
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    @ApiModelProperty(value = "生产厂商")
    private String sccs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMRESOURCE.gg
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    @ApiModelProperty(value = "规格")
    private String gg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMRESOURCE.pic
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    @ApiModelProperty(value = "投入品图片")
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMRESOURCE.sybz
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    @ApiModelProperty(value = "使用备注")
    private String sybz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FARMRESOURCE.unit
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    @ApiModelProperty(value = "单位")
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMRESOURCE.bh
     *
     * @return the value of FARMRESOURCE.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMRESOURCE.bh
     *
     * @param bh the value for FARMRESOURCE.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMRESOURCE.type
     *
     * @return the value of FARMRESOURCE.type
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMRESOURCE.type
     *
     * @param type the value for FARMRESOURCE.type
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMRESOURCE.mc
     *
     * @return the value of FARMRESOURCE.mc
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMRESOURCE.mc
     *
     * @param mc the value for FARMRESOURCE.mc
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMRESOURCE.sccs
     *
     * @return the value of FARMRESOURCE.sccs
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getSccs() {
        return sccs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMRESOURCE.sccs
     *
     * @param sccs the value for FARMRESOURCE.sccs
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setSccs(String sccs) {
        this.sccs = sccs == null ? null : sccs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMRESOURCE.gg
     *
     * @return the value of FARMRESOURCE.gg
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getGg() {
        return gg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMRESOURCE.gg
     *
     * @param gg the value for FARMRESOURCE.gg
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setGg(String gg) {
        this.gg = gg == null ? null : gg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMRESOURCE.pic
     *
     * @return the value of FARMRESOURCE.pic
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMRESOURCE.pic
     *
     * @param pic the value for FARMRESOURCE.pic
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMRESOURCE.sybz
     *
     * @return the value of FARMRESOURCE.sybz
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getSybz() {
        return sybz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMRESOURCE.sybz
     *
     * @param sybz the value for FARMRESOURCE.sybz
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setSybz(String sybz) {
        this.sybz = sybz == null ? null : sybz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FARMRESOURCE.unit
     *
     * @return the value of FARMRESOURCE.unit
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FARMRESOURCE.unit
     *
     * @param unit the value for FARMRESOURCE.unit
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}