package com.clesun.web.skyland.entity;

import java.util.ArrayList;
import java.util.List;

public class ParcelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    protected int offset = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public ParcelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public void setOffset(int offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFidIsNull() {
            addCriterion("fid is null");
            return (Criteria) this;
        }

        public Criteria andFidIsNotNull() {
            addCriterion("fid is not null");
            return (Criteria) this;
        }

        public Criteria andFidEqualTo(Integer value) {
            addCriterion("fid =", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotEqualTo(Integer value) {
            addCriterion("fid <>", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThan(Integer value) {
            addCriterion("fid >", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThanOrEqualTo(Integer value) {
            addCriterion("fid >=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThan(Integer value) {
            addCriterion("fid <", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThanOrEqualTo(Integer value) {
            addCriterion("fid <=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidIn(List<Integer> values) {
            addCriterion("fid in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotIn(List<Integer> values) {
            addCriterion("fid not in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidBetween(Integer value1, Integer value2) {
            addCriterion("fid between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotBetween(Integer value1, Integer value2) {
            addCriterion("fid not between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andTheGeomIsNull() {
            addCriterion("the_geom is null");
            return (Criteria) this;
        }

        public Criteria andTheGeomIsNotNull() {
            addCriterion("the_geom is not null");
            return (Criteria) this;
        }

        public Criteria andTheGeomEqualTo(Object value) {
            addCriterion("the_geom =", value, "theGeom");
            return (Criteria) this;
        }

        public Criteria andTheGeomNotEqualTo(Object value) {
            addCriterion("the_geom <>", value, "theGeom");
            return (Criteria) this;
        }

        public Criteria andTheGeomGreaterThan(Object value) {
            addCriterion("the_geom >", value, "theGeom");
            return (Criteria) this;
        }

        public Criteria andTheGeomGreaterThanOrEqualTo(Object value) {
            addCriterion("the_geom >=", value, "theGeom");
            return (Criteria) this;
        }

        public Criteria andTheGeomLessThan(Object value) {
            addCriterion("the_geom <", value, "theGeom");
            return (Criteria) this;
        }

        public Criteria andTheGeomLessThanOrEqualTo(Object value) {
            addCriterion("the_geom <=", value, "theGeom");
            return (Criteria) this;
        }

        public Criteria andTheGeomIn(List<Object> values) {
            addCriterion("the_geom in", values, "theGeom");
            return (Criteria) this;
        }

        public Criteria andTheGeomNotIn(List<Object> values) {
            addCriterion("the_geom not in", values, "theGeom");
            return (Criteria) this;
        }

        public Criteria andTheGeomBetween(Object value1, Object value2) {
            addCriterion("the_geom between", value1, value2, "theGeom");
            return (Criteria) this;
        }

        public Criteria andTheGeomNotBetween(Object value1, Object value2) {
            addCriterion("the_geom not between", value1, value2, "theGeom");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("Id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("Id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMjIsNull() {
            addCriterion("MJ is null");
            return (Criteria) this;
        }

        public Criteria andMjIsNotNull() {
            addCriterion("MJ is not null");
            return (Criteria) this;
        }

        public Criteria andMjEqualTo(Double value) {
            addCriterion("MJ =", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjNotEqualTo(Double value) {
            addCriterion("MJ <>", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjGreaterThan(Double value) {
            addCriterion("MJ >", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjGreaterThanOrEqualTo(Double value) {
            addCriterion("MJ >=", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjLessThan(Double value) {
            addCriterion("MJ <", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjLessThanOrEqualTo(Double value) {
            addCriterion("MJ <=", value, "mj");
            return (Criteria) this;
        }

        public Criteria andMjIn(List<Double> values) {
            addCriterion("MJ in", values, "mj");
            return (Criteria) this;
        }

        public Criteria andMjNotIn(List<Double> values) {
            addCriterion("MJ not in", values, "mj");
            return (Criteria) this;
        }

        public Criteria andMjBetween(Double value1, Double value2) {
            addCriterion("MJ between", value1, value2, "mj");
            return (Criteria) this;
        }

        public Criteria andMjNotBetween(Double value1, Double value2) {
            addCriterion("MJ not between", value1, value2, "mj");
            return (Criteria) this;
        }

        public Criteria andMcIsNull() {
            addCriterion("MC is null");
            return (Criteria) this;
        }

        public Criteria andMcIsNotNull() {
            addCriterion("MC is not null");
            return (Criteria) this;
        }

        public Criteria andMcEqualTo(String value) {
            addCriterion("MC =", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotEqualTo(String value) {
            addCriterion("MC <>", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcGreaterThan(String value) {
            addCriterion("MC >", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcGreaterThanOrEqualTo(String value) {
            addCriterion("MC >=", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcLessThan(String value) {
            addCriterion("MC <", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcLessThanOrEqualTo(String value) {
            addCriterion("MC <=", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcLike(String value) {
            addCriterion("MC like", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotLike(String value) {
            addCriterion("MC not like", value, "mc");
            return (Criteria) this;
        }

        public Criteria andMcIn(List<String> values) {
            addCriterion("MC in", values, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotIn(List<String> values) {
            addCriterion("MC not in", values, "mc");
            return (Criteria) this;
        }

        public Criteria andMcBetween(String value1, String value2) {
            addCriterion("MC between", value1, value2, "mc");
            return (Criteria) this;
        }

        public Criteria andMcNotBetween(String value1, String value2) {
            addCriterion("MC not between", value1, value2, "mc");
            return (Criteria) this;
        }

        public Criteria andSsqymcIsNull() {
            addCriterion("SSQYMC is null");
            return (Criteria) this;
        }

        public Criteria andSsqymcIsNotNull() {
            addCriterion("SSQYMC is not null");
            return (Criteria) this;
        }

        public Criteria andSsqymcEqualTo(String value) {
            addCriterion("SSQYMC =", value, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcNotEqualTo(String value) {
            addCriterion("SSQYMC <>", value, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcGreaterThan(String value) {
            addCriterion("SSQYMC >", value, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcGreaterThanOrEqualTo(String value) {
            addCriterion("SSQYMC >=", value, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcLessThan(String value) {
            addCriterion("SSQYMC <", value, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcLessThanOrEqualTo(String value) {
            addCriterion("SSQYMC <=", value, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcLike(String value) {
            addCriterion("SSQYMC like", value, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcNotLike(String value) {
            addCriterion("SSQYMC not like", value, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcIn(List<String> values) {
            addCriterion("SSQYMC in", values, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcNotIn(List<String> values) {
            addCriterion("SSQYMC not in", values, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcBetween(String value1, String value2) {
            addCriterion("SSQYMC between", value1, value2, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqymcNotBetween(String value1, String value2) {
            addCriterion("SSQYMC not between", value1, value2, "ssqymc");
            return (Criteria) this;
        }

        public Criteria andSsqybmIsNull() {
            addCriterion("SSQYBM is null");
            return (Criteria) this;
        }

        public Criteria andSsqybmIsNotNull() {
            addCriterion("SSQYBM is not null");
            return (Criteria) this;
        }

        public Criteria andSsqybmEqualTo(String value) {
            addCriterion("SSQYBM =", value, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmNotEqualTo(String value) {
            addCriterion("SSQYBM <>", value, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmGreaterThan(String value) {
            addCriterion("SSQYBM >", value, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmGreaterThanOrEqualTo(String value) {
            addCriterion("SSQYBM >=", value, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmLessThan(String value) {
            addCriterion("SSQYBM <", value, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmLessThanOrEqualTo(String value) {
            addCriterion("SSQYBM <=", value, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmLike(String value) {
            addCriterion("SSQYBM like", value, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmNotLike(String value) {
            addCriterion("SSQYBM not like", value, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmIn(List<String> values) {
            addCriterion("SSQYBM in", values, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmNotIn(List<String> values) {
            addCriterion("SSQYBM not in", values, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmBetween(String value1, String value2) {
            addCriterion("SSQYBM between", value1, value2, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andSsqybmNotBetween(String value1, String value2) {
            addCriterion("SSQYBM not between", value1, value2, "ssqybm");
            return (Criteria) this;
        }

        public Criteria andDklxIsNull() {
            addCriterion("DKLX is null");
            return (Criteria) this;
        }

        public Criteria andDklxIsNotNull() {
            addCriterion("DKLX is not null");
            return (Criteria) this;
        }

        public Criteria andDklxEqualTo(String value) {
            addCriterion("DKLX =", value, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxNotEqualTo(String value) {
            addCriterion("DKLX <>", value, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxGreaterThan(String value) {
            addCriterion("DKLX >", value, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxGreaterThanOrEqualTo(String value) {
            addCriterion("DKLX >=", value, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxLessThan(String value) {
            addCriterion("DKLX <", value, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxLessThanOrEqualTo(String value) {
            addCriterion("DKLX <=", value, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxLike(String value) {
            addCriterion("DKLX like", value, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxNotLike(String value) {
            addCriterion("DKLX not like", value, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxIn(List<String> values) {
            addCriterion("DKLX in", values, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxNotIn(List<String> values) {
            addCriterion("DKLX not in", values, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxBetween(String value1, String value2) {
            addCriterion("DKLX between", value1, value2, "dklx");
            return (Criteria) this;
        }

        public Criteria andDklxNotBetween(String value1, String value2) {
            addCriterion("DKLX not between", value1, value2, "dklx");
            return (Criteria) this;
        }

        public Criteria andDldjIsNull() {
            addCriterion("DLDJ is null");
            return (Criteria) this;
        }

        public Criteria andDldjIsNotNull() {
            addCriterion("DLDJ is not null");
            return (Criteria) this;
        }

        public Criteria andDldjEqualTo(String value) {
            addCriterion("DLDJ =", value, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjNotEqualTo(String value) {
            addCriterion("DLDJ <>", value, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjGreaterThan(String value) {
            addCriterion("DLDJ >", value, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjGreaterThanOrEqualTo(String value) {
            addCriterion("DLDJ >=", value, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjLessThan(String value) {
            addCriterion("DLDJ <", value, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjLessThanOrEqualTo(String value) {
            addCriterion("DLDJ <=", value, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjLike(String value) {
            addCriterion("DLDJ like", value, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjNotLike(String value) {
            addCriterion("DLDJ not like", value, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjIn(List<String> values) {
            addCriterion("DLDJ in", values, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjNotIn(List<String> values) {
            addCriterion("DLDJ not in", values, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjBetween(String value1, String value2) {
            addCriterion("DLDJ between", value1, value2, "dldj");
            return (Criteria) this;
        }

        public Criteria andDldjNotBetween(String value1, String value2) {
            addCriterion("DLDJ not between", value1, value2, "dldj");
            return (Criteria) this;
        }

        public Criteria andMsIsNull() {
            addCriterion("MS is null");
            return (Criteria) this;
        }

        public Criteria andMsIsNotNull() {
            addCriterion("MS is not null");
            return (Criteria) this;
        }

        public Criteria andMsEqualTo(String value) {
            addCriterion("MS =", value, "ms");
            return (Criteria) this;
        }

        public Criteria andMsNotEqualTo(String value) {
            addCriterion("MS <>", value, "ms");
            return (Criteria) this;
        }

        public Criteria andMsGreaterThan(String value) {
            addCriterion("MS >", value, "ms");
            return (Criteria) this;
        }

        public Criteria andMsGreaterThanOrEqualTo(String value) {
            addCriterion("MS >=", value, "ms");
            return (Criteria) this;
        }

        public Criteria andMsLessThan(String value) {
            addCriterion("MS <", value, "ms");
            return (Criteria) this;
        }

        public Criteria andMsLessThanOrEqualTo(String value) {
            addCriterion("MS <=", value, "ms");
            return (Criteria) this;
        }

        public Criteria andMsLike(String value) {
            addCriterion("MS like", value, "ms");
            return (Criteria) this;
        }

        public Criteria andMsNotLike(String value) {
            addCriterion("MS not like", value, "ms");
            return (Criteria) this;
        }

        public Criteria andMsIn(List<String> values) {
            addCriterion("MS in", values, "ms");
            return (Criteria) this;
        }

        public Criteria andMsNotIn(List<String> values) {
            addCriterion("MS not in", values, "ms");
            return (Criteria) this;
        }

        public Criteria andMsBetween(String value1, String value2) {
            addCriterion("MS between", value1, value2, "ms");
            return (Criteria) this;
        }

        public Criteria andMsNotBetween(String value1, String value2) {
            addCriterion("MS not between", value1, value2, "ms");
            return (Criteria) this;
        }

        public Criteria andOwnerunitIsNull() {
            addCriterion("ownerUnit is null");
            return (Criteria) this;
        }

        public Criteria andOwnerunitIsNotNull() {
            addCriterion("ownerUnit is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerunitEqualTo(String value) {
            addCriterion("ownerUnit =", value, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitNotEqualTo(String value) {
            addCriterion("ownerUnit <>", value, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitGreaterThan(String value) {
            addCriterion("ownerUnit >", value, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitGreaterThanOrEqualTo(String value) {
            addCriterion("ownerUnit >=", value, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitLessThan(String value) {
            addCriterion("ownerUnit <", value, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitLessThanOrEqualTo(String value) {
            addCriterion("ownerUnit <=", value, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitLike(String value) {
            addCriterion("ownerUnit like", value, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitNotLike(String value) {
            addCriterion("ownerUnit not like", value, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitIn(List<String> values) {
            addCriterion("ownerUnit in", values, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitNotIn(List<String> values) {
            addCriterion("ownerUnit not in", values, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitBetween(String value1, String value2) {
            addCriterion("ownerUnit between", value1, value2, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andOwnerunitNotBetween(String value1, String value2) {
            addCriterion("ownerUnit not between", value1, value2, "ownerunit");
            return (Criteria) this;
        }

        public Criteria andZrzIsNull() {
            addCriterion("ZRZ is null");
            return (Criteria) this;
        }

        public Criteria andZrzIsNotNull() {
            addCriterion("ZRZ is not null");
            return (Criteria) this;
        }

        public Criteria andZrzEqualTo(String value) {
            addCriterion("ZRZ =", value, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzNotEqualTo(String value) {
            addCriterion("ZRZ <>", value, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzGreaterThan(String value) {
            addCriterion("ZRZ >", value, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzGreaterThanOrEqualTo(String value) {
            addCriterion("ZRZ >=", value, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzLessThan(String value) {
            addCriterion("ZRZ <", value, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzLessThanOrEqualTo(String value) {
            addCriterion("ZRZ <=", value, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzLike(String value) {
            addCriterion("ZRZ like", value, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzNotLike(String value) {
            addCriterion("ZRZ not like", value, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzIn(List<String> values) {
            addCriterion("ZRZ in", values, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzNotIn(List<String> values) {
            addCriterion("ZRZ not in", values, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzBetween(String value1, String value2) {
            addCriterion("ZRZ between", value1, value2, "zrz");
            return (Criteria) this;
        }

        public Criteria andZrzNotBetween(String value1, String value2) {
            addCriterion("ZRZ not between", value1, value2, "zrz");
            return (Criteria) this;
        }

        public Criteria andShapeStarIsNull() {
            addCriterion("Shape_STAr is null");
            return (Criteria) this;
        }

        public Criteria andShapeStarIsNotNull() {
            addCriterion("Shape_STAr is not null");
            return (Criteria) this;
        }

        public Criteria andShapeStarEqualTo(Double value) {
            addCriterion("Shape_STAr =", value, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStarNotEqualTo(Double value) {
            addCriterion("Shape_STAr <>", value, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStarGreaterThan(Double value) {
            addCriterion("Shape_STAr >", value, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStarGreaterThanOrEqualTo(Double value) {
            addCriterion("Shape_STAr >=", value, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStarLessThan(Double value) {
            addCriterion("Shape_STAr <", value, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStarLessThanOrEqualTo(Double value) {
            addCriterion("Shape_STAr <=", value, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStarIn(List<Double> values) {
            addCriterion("Shape_STAr in", values, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStarNotIn(List<Double> values) {
            addCriterion("Shape_STAr not in", values, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStarBetween(Double value1, Double value2) {
            addCriterion("Shape_STAr between", value1, value2, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStarNotBetween(Double value1, Double value2) {
            addCriterion("Shape_STAr not between", value1, value2, "shapeStar");
            return (Criteria) this;
        }

        public Criteria andShapeStleIsNull() {
            addCriterion("Shape_STLe is null");
            return (Criteria) this;
        }

        public Criteria andShapeStleIsNotNull() {
            addCriterion("Shape_STLe is not null");
            return (Criteria) this;
        }

        public Criteria andShapeStleEqualTo(Double value) {
            addCriterion("Shape_STLe =", value, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andShapeStleNotEqualTo(Double value) {
            addCriterion("Shape_STLe <>", value, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andShapeStleGreaterThan(Double value) {
            addCriterion("Shape_STLe >", value, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andShapeStleGreaterThanOrEqualTo(Double value) {
            addCriterion("Shape_STLe >=", value, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andShapeStleLessThan(Double value) {
            addCriterion("Shape_STLe <", value, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andShapeStleLessThanOrEqualTo(Double value) {
            addCriterion("Shape_STLe <=", value, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andShapeStleIn(List<Double> values) {
            addCriterion("Shape_STLe in", values, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andShapeStleNotIn(List<Double> values) {
            addCriterion("Shape_STLe not in", values, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andShapeStleBetween(Double value1, Double value2) {
            addCriterion("Shape_STLe between", value1, value2, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andShapeStleNotBetween(Double value1, Double value2) {
            addCriterion("Shape_STLe not between", value1, value2, "shapeStle");
            return (Criteria) this;
        }

        public Criteria andIsnydIsNull() {
            addCriterion("isNYD is null");
            return (Criteria) this;
        }

        public Criteria andIsnydIsNotNull() {
            addCriterion("isNYD is not null");
            return (Criteria) this;
        }

        public Criteria andIsnydEqualTo(String value) {
            addCriterion("isNYD =", value, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydNotEqualTo(String value) {
            addCriterion("isNYD <>", value, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydGreaterThan(String value) {
            addCriterion("isNYD >", value, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydGreaterThanOrEqualTo(String value) {
            addCriterion("isNYD >=", value, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydLessThan(String value) {
            addCriterion("isNYD <", value, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydLessThanOrEqualTo(String value) {
            addCriterion("isNYD <=", value, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydLike(String value) {
            addCriterion("isNYD like", value, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydNotLike(String value) {
            addCriterion("isNYD not like", value, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydIn(List<String> values) {
            addCriterion("isNYD in", values, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydNotIn(List<String> values) {
            addCriterion("isNYD not in", values, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydBetween(String value1, String value2) {
            addCriterion("isNYD between", value1, value2, "isnyd");
            return (Criteria) this;
        }

        public Criteria andIsnydNotBetween(String value1, String value2) {
            addCriterion("isNYD not between", value1, value2, "isnyd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PARCEL
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 21 16:50:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PARCEL
     *
     * @mbggenerated Mon Jan 21 16:50:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}