package com.clesun.web.skyland.entity;

import java.util.Date;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.ygbm
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String ygbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.xm
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.xb
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.dob
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private Date dob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.zjlx
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String zjlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.zjh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String zjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.lxfs
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String lxfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.bz
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.username
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.password
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.pic
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.bh
     *
     * @return the value of PERSON.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.bh
     *
     * @param bh the value for PERSON.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.ygbm
     *
     * @return the value of PERSON.ygbm
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getYgbm() {
        return ygbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.ygbm
     *
     * @param ygbm the value for PERSON.ygbm
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setYgbm(String ygbm) {
        this.ygbm = ygbm == null ? null : ygbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.xm
     *
     * @return the value of PERSON.xm
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.xm
     *
     * @param xm the value for PERSON.xm
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.xb
     *
     * @return the value of PERSON.xb
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.xb
     *
     * @param xb the value for PERSON.xb
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.dob
     *
     * @return the value of PERSON.dob
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public Date getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.dob
     *
     * @param dob the value for PERSON.dob
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.zjlx
     *
     * @return the value of PERSON.zjlx
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getZjlx() {
        return zjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.zjlx
     *
     * @param zjlx the value for PERSON.zjlx
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setZjlx(String zjlx) {
        this.zjlx = zjlx == null ? null : zjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.zjh
     *
     * @return the value of PERSON.zjh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getZjh() {
        return zjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.zjh
     *
     * @param zjh the value for PERSON.zjh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setZjh(String zjh) {
        this.zjh = zjh == null ? null : zjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.lxfs
     *
     * @return the value of PERSON.lxfs
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getLxfs() {
        return lxfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.lxfs
     *
     * @param lxfs the value for PERSON.lxfs
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setLxfs(String lxfs) {
        this.lxfs = lxfs == null ? null : lxfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.bz
     *
     * @return the value of PERSON.bz
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.bz
     *
     * @param bz the value for PERSON.bz
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.username
     *
     * @return the value of PERSON.username
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.username
     *
     * @param username the value for PERSON.username
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.password
     *
     * @return the value of PERSON.password
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.password
     *
     * @param password the value for PERSON.password
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.pic
     *
     * @return the value of PERSON.pic
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.pic
     *
     * @param pic the value for PERSON.pic
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }
}