package com.clesun.web.skyland.entity;

public class Plant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANT.bh
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANT.mc
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANT.xm
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANT.bm
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    private String bm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANT.ssxl
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    private String ssxl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANT.ke
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    private String ke;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANT.shu
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    private String shu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANT.pic
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANT.bz
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANT.bh
     *
     * @return the value of PLANT.bh
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANT.bh
     *
     * @param bh the value for PLANT.bh
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANT.mc
     *
     * @return the value of PLANT.mc
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANT.mc
     *
     * @param mc the value for PLANT.mc
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANT.xm
     *
     * @return the value of PLANT.xm
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANT.xm
     *
     * @param xm the value for PLANT.xm
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANT.bm
     *
     * @return the value of PLANT.bm
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public String getBm() {
        return bm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANT.bm
     *
     * @param bm the value for PLANT.bm
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public void setBm(String bm) {
        this.bm = bm == null ? null : bm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANT.ssxl
     *
     * @return the value of PLANT.ssxl
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public String getSsxl() {
        return ssxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANT.ssxl
     *
     * @param ssxl the value for PLANT.ssxl
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public void setSsxl(String ssxl) {
        this.ssxl = ssxl == null ? null : ssxl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANT.ke
     *
     * @return the value of PLANT.ke
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public String getKe() {
        return ke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANT.ke
     *
     * @param ke the value for PLANT.ke
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public void setKe(String ke) {
        this.ke = ke == null ? null : ke.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANT.shu
     *
     * @return the value of PLANT.shu
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public String getShu() {
        return shu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANT.shu
     *
     * @param shu the value for PLANT.shu
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public void setShu(String shu) {
        this.shu = shu == null ? null : shu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANT.pic
     *
     * @return the value of PLANT.pic
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANT.pic
     *
     * @param pic the value for PLANT.pic
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANT.bz
     *
     * @return the value of PLANT.bz
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANT.bz
     *
     * @param bz the value for PLANT.bz
     *
     * @mbggenerated Mon Jan 07 15:34:47 CST 2019
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}