package com.clesun.web.skyland.entity;

import java.util.Date;

public class Plantrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANTRECORD.bh
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANTRECORD.plantbh
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    private String plantbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANTRECORD.parcelbh
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    private String parcelbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANTRECORD.area
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANTRECORD.sdate
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    private Date sdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLANTRECORD.edate
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    private Date edate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANTRECORD.bh
     *
     * @return the value of PLANTRECORD.bh
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANTRECORD.bh
     *
     * @param bh the value for PLANTRECORD.bh
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANTRECORD.plantbh
     *
     * @return the value of PLANTRECORD.plantbh
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public String getPlantbh() {
        return plantbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANTRECORD.plantbh
     *
     * @param plantbh the value for PLANTRECORD.plantbh
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public void setPlantbh(String plantbh) {
        this.plantbh = plantbh == null ? null : plantbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANTRECORD.parcelbh
     *
     * @return the value of PLANTRECORD.parcelbh
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public String getParcelbh() {
        return parcelbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANTRECORD.parcelbh
     *
     * @param parcelbh the value for PLANTRECORD.parcelbh
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public void setParcelbh(String parcelbh) {
        this.parcelbh = parcelbh == null ? null : parcelbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANTRECORD.area
     *
     * @return the value of PLANTRECORD.area
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANTRECORD.area
     *
     * @param area the value for PLANTRECORD.area
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANTRECORD.sdate
     *
     * @return the value of PLANTRECORD.sdate
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public Date getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANTRECORD.sdate
     *
     * @param sdate the value for PLANTRECORD.sdate
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLANTRECORD.edate
     *
     * @return the value of PLANTRECORD.edate
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public Date getEdate() {
        return edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLANTRECORD.edate
     *
     * @param edate the value for PLANTRECORD.edate
     *
     * @mbggenerated Tue Jan 08 09:35:44 CST 2019
     */
    public void setEdate(Date edate) {
        this.edate = edate;
    }
}