package com.clesun.web.skyland.entity;

public class Resourcerecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCERECORD.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCERECORD.workbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String workbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCERECORD.resourcebh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String resourcebh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCERECORD.amount
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCERECORD.bh
     *
     * @return the value of RESOURCERECORD.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCERECORD.bh
     *
     * @param bh the value for RESOURCERECORD.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCERECORD.workbh
     *
     * @return the value of RESOURCERECORD.workbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getWorkbh() {
        return workbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCERECORD.workbh
     *
     * @param workbh the value for RESOURCERECORD.workbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setWorkbh(String workbh) {
        this.workbh = workbh == null ? null : workbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCERECORD.resourcebh
     *
     * @return the value of RESOURCERECORD.resourcebh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getResourcebh() {
        return resourcebh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCERECORD.resourcebh
     *
     * @param resourcebh the value for RESOURCERECORD.resourcebh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setResourcebh(String resourcebh) {
        this.resourcebh = resourcebh == null ? null : resourcebh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCERECORD.amount
     *
     * @return the value of RESOURCERECORD.amount
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCERECORD.amount
     *
     * @param amount the value for RESOURCERECORD.amount
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }
}