package com.clesun.web.skyland.entity;

import java.util.Date;

public class Workrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKRECORD.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKRECORD.workbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String workbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKRECORD.plantrecordbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String plantrecordbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKRECORD.personbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String personbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKRECORD.opertime
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private Date opertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKRECORD.hours
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String hours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKRECORD.type
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKRECORD.bz
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKRECORD.bh
     *
     * @return the value of WORKRECORD.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKRECORD.bh
     *
     * @param bh the value for WORKRECORD.bh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKRECORD.workbh
     *
     * @return the value of WORKRECORD.workbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getWorkbh() {
        return workbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKRECORD.workbh
     *
     * @param workbh the value for WORKRECORD.workbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setWorkbh(String workbh) {
        this.workbh = workbh == null ? null : workbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKRECORD.plantrecordbh
     *
     * @return the value of WORKRECORD.plantrecordbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getPlantrecordbh() {
        return plantrecordbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKRECORD.plantrecordbh
     *
     * @param plantrecordbh the value for WORKRECORD.plantrecordbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setPlantrecordbh(String plantrecordbh) {
        this.plantrecordbh = plantrecordbh == null ? null : plantrecordbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKRECORD.personbh
     *
     * @return the value of WORKRECORD.personbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getPersonbh() {
        return personbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKRECORD.personbh
     *
     * @param personbh the value for WORKRECORD.personbh
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setPersonbh(String personbh) {
        this.personbh = personbh == null ? null : personbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKRECORD.opertime
     *
     * @return the value of WORKRECORD.opertime
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKRECORD.opertime
     *
     * @param opertime the value for WORKRECORD.opertime
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKRECORD.hours
     *
     * @return the value of WORKRECORD.hours
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getHours() {
        return hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKRECORD.hours
     *
     * @param hours the value for WORKRECORD.hours
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setHours(String hours) {
        this.hours = hours == null ? null : hours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKRECORD.type
     *
     * @return the value of WORKRECORD.type
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKRECORD.type
     *
     * @param type the value for WORKRECORD.type
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKRECORD.bz
     *
     * @return the value of WORKRECORD.bz
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKRECORD.bz
     *
     * @param bz the value for WORKRECORD.bz
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}