package com.clesun.web.skyland.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WorkrecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    protected int offset = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public WorkrecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setOffset(int offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBhIsNull() {
            addCriterion("bh is null");
            return (Criteria) this;
        }

        public Criteria andBhIsNotNull() {
            addCriterion("bh is not null");
            return (Criteria) this;
        }

        public Criteria andBhEqualTo(String value) {
            addCriterion("bh =", value, "bh");
            return (Criteria) this;
        }

        public Criteria andBhNotEqualTo(String value) {
            addCriterion("bh <>", value, "bh");
            return (Criteria) this;
        }

        public Criteria andBhGreaterThan(String value) {
            addCriterion("bh >", value, "bh");
            return (Criteria) this;
        }

        public Criteria andBhGreaterThanOrEqualTo(String value) {
            addCriterion("bh >=", value, "bh");
            return (Criteria) this;
        }

        public Criteria andBhLessThan(String value) {
            addCriterion("bh <", value, "bh");
            return (Criteria) this;
        }

        public Criteria andBhLessThanOrEqualTo(String value) {
            addCriterion("bh <=", value, "bh");
            return (Criteria) this;
        }

        public Criteria andBhLike(String value) {
            addCriterion("bh like", value, "bh");
            return (Criteria) this;
        }

        public Criteria andBhNotLike(String value) {
            addCriterion("bh not like", value, "bh");
            return (Criteria) this;
        }

        public Criteria andBhIn(List<String> values) {
            addCriterion("bh in", values, "bh");
            return (Criteria) this;
        }

        public Criteria andBhNotIn(List<String> values) {
            addCriterion("bh not in", values, "bh");
            return (Criteria) this;
        }

        public Criteria andBhBetween(String value1, String value2) {
            addCriterion("bh between", value1, value2, "bh");
            return (Criteria) this;
        }

        public Criteria andBhNotBetween(String value1, String value2) {
            addCriterion("bh not between", value1, value2, "bh");
            return (Criteria) this;
        }

        public Criteria andWorkbhIsNull() {
            addCriterion("workbh is null");
            return (Criteria) this;
        }

        public Criteria andWorkbhIsNotNull() {
            addCriterion("workbh is not null");
            return (Criteria) this;
        }

        public Criteria andWorkbhEqualTo(String value) {
            addCriterion("workbh =", value, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhNotEqualTo(String value) {
            addCriterion("workbh <>", value, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhGreaterThan(String value) {
            addCriterion("workbh >", value, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhGreaterThanOrEqualTo(String value) {
            addCriterion("workbh >=", value, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhLessThan(String value) {
            addCriterion("workbh <", value, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhLessThanOrEqualTo(String value) {
            addCriterion("workbh <=", value, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhLike(String value) {
            addCriterion("workbh like", value, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhNotLike(String value) {
            addCriterion("workbh not like", value, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhIn(List<String> values) {
            addCriterion("workbh in", values, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhNotIn(List<String> values) {
            addCriterion("workbh not in", values, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhBetween(String value1, String value2) {
            addCriterion("workbh between", value1, value2, "workbh");
            return (Criteria) this;
        }

        public Criteria andWorkbhNotBetween(String value1, String value2) {
            addCriterion("workbh not between", value1, value2, "workbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhIsNull() {
            addCriterion("plantrecordbh is null");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhIsNotNull() {
            addCriterion("plantrecordbh is not null");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhEqualTo(String value) {
            addCriterion("plantrecordbh =", value, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhNotEqualTo(String value) {
            addCriterion("plantrecordbh <>", value, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhGreaterThan(String value) {
            addCriterion("plantrecordbh >", value, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhGreaterThanOrEqualTo(String value) {
            addCriterion("plantrecordbh >=", value, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhLessThan(String value) {
            addCriterion("plantrecordbh <", value, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhLessThanOrEqualTo(String value) {
            addCriterion("plantrecordbh <=", value, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhLike(String value) {
            addCriterion("plantrecordbh like", value, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhNotLike(String value) {
            addCriterion("plantrecordbh not like", value, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhIn(List<String> values) {
            addCriterion("plantrecordbh in", values, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhNotIn(List<String> values) {
            addCriterion("plantrecordbh not in", values, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhBetween(String value1, String value2) {
            addCriterion("plantrecordbh between", value1, value2, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPlantrecordbhNotBetween(String value1, String value2) {
            addCriterion("plantrecordbh not between", value1, value2, "plantrecordbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhIsNull() {
            addCriterion("personbh is null");
            return (Criteria) this;
        }

        public Criteria andPersonbhIsNotNull() {
            addCriterion("personbh is not null");
            return (Criteria) this;
        }

        public Criteria andPersonbhEqualTo(String value) {
            addCriterion("personbh =", value, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhNotEqualTo(String value) {
            addCriterion("personbh <>", value, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhGreaterThan(String value) {
            addCriterion("personbh >", value, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhGreaterThanOrEqualTo(String value) {
            addCriterion("personbh >=", value, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhLessThan(String value) {
            addCriterion("personbh <", value, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhLessThanOrEqualTo(String value) {
            addCriterion("personbh <=", value, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhLike(String value) {
            addCriterion("personbh like", value, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhNotLike(String value) {
            addCriterion("personbh not like", value, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhIn(List<String> values) {
            addCriterion("personbh in", values, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhNotIn(List<String> values) {
            addCriterion("personbh not in", values, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhBetween(String value1, String value2) {
            addCriterion("personbh between", value1, value2, "personbh");
            return (Criteria) this;
        }

        public Criteria andPersonbhNotBetween(String value1, String value2) {
            addCriterion("personbh not between", value1, value2, "personbh");
            return (Criteria) this;
        }

        public Criteria andOpertimeIsNull() {
            addCriterion("opertime is null");
            return (Criteria) this;
        }

        public Criteria andOpertimeIsNotNull() {
            addCriterion("opertime is not null");
            return (Criteria) this;
        }

        public Criteria andOpertimeEqualTo(Date value) {
            addCriterion("opertime =", value, "opertime");
            return (Criteria) this;
        }

        public Criteria andOpertimeNotEqualTo(Date value) {
            addCriterion("opertime <>", value, "opertime");
            return (Criteria) this;
        }

        public Criteria andOpertimeGreaterThan(Date value) {
            addCriterion("opertime >", value, "opertime");
            return (Criteria) this;
        }

        public Criteria andOpertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("opertime >=", value, "opertime");
            return (Criteria) this;
        }

        public Criteria andOpertimeLessThan(Date value) {
            addCriterion("opertime <", value, "opertime");
            return (Criteria) this;
        }

        public Criteria andOpertimeLessThanOrEqualTo(Date value) {
            addCriterion("opertime <=", value, "opertime");
            return (Criteria) this;
        }

        public Criteria andOpertimeIn(List<Date> values) {
            addCriterion("opertime in", values, "opertime");
            return (Criteria) this;
        }

        public Criteria andOpertimeNotIn(List<Date> values) {
            addCriterion("opertime not in", values, "opertime");
            return (Criteria) this;
        }

        public Criteria andOpertimeBetween(Date value1, Date value2) {
            addCriterion("opertime between", value1, value2, "opertime");
            return (Criteria) this;
        }

        public Criteria andOpertimeNotBetween(Date value1, Date value2) {
            addCriterion("opertime not between", value1, value2, "opertime");
            return (Criteria) this;
        }

        public Criteria andHoursIsNull() {
            addCriterion("hours is null");
            return (Criteria) this;
        }

        public Criteria andHoursIsNotNull() {
            addCriterion("hours is not null");
            return (Criteria) this;
        }

        public Criteria andHoursEqualTo(String value) {
            addCriterion("hours =", value, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursNotEqualTo(String value) {
            addCriterion("hours <>", value, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursGreaterThan(String value) {
            addCriterion("hours >", value, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursGreaterThanOrEqualTo(String value) {
            addCriterion("hours >=", value, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursLessThan(String value) {
            addCriterion("hours <", value, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursLessThanOrEqualTo(String value) {
            addCriterion("hours <=", value, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursLike(String value) {
            addCriterion("hours like", value, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursNotLike(String value) {
            addCriterion("hours not like", value, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursIn(List<String> values) {
            addCriterion("hours in", values, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursNotIn(List<String> values) {
            addCriterion("hours not in", values, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursBetween(String value1, String value2) {
            addCriterion("hours between", value1, value2, "hours");
            return (Criteria) this;
        }

        public Criteria andHoursNotBetween(String value1, String value2) {
            addCriterion("hours not between", value1, value2, "hours");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("bz is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("bz is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("bz =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("bz <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("bz >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("bz >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("bz <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("bz <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("bz like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("bz not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("bz in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("bz not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("bz between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("bz not between", value1, value2, "bz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WORKRECORD
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 18 14:46:02 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WORKRECORD
     *
     * @mbggenerated Fri Jan 18 14:46:02 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}