package com.clesun.web.skyland.entity;

public class ZhnyNsxqTrp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSXQ_TRP.id
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSXQ_TRP.NSXQ_ID
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private Integer nsxqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSXQ_TRP.NZMC
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String nzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSXQ_TRP.NZLB
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String nzlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSXQ_TRP.NZYL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private Double nzyl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSXQ_TRP.NZBZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String nzbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSXQ_TRP.NZTPDZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String nztpdz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSXQ_TRP.id
     *
     * @return the value of ZHNY_NSXQ_TRP.id
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSXQ_TRP.id
     *
     * @param id the value for ZHNY_NSXQ_TRP.id
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSXQ_TRP.NSXQ_ID
     *
     * @return the value of ZHNY_NSXQ_TRP.NSXQ_ID
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public Integer getNsxqId() {
        return nsxqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSXQ_TRP.NSXQ_ID
     *
     * @param nsxqId the value for ZHNY_NSXQ_TRP.NSXQ_ID
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setNsxqId(Integer nsxqId) {
        this.nsxqId = nsxqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSXQ_TRP.NZMC
     *
     * @return the value of ZHNY_NSXQ_TRP.NZMC
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getNzmc() {
        return nzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSXQ_TRP.NZMC
     *
     * @param nzmc the value for ZHNY_NSXQ_TRP.NZMC
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setNzmc(String nzmc) {
        this.nzmc = nzmc == null ? null : nzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSXQ_TRP.NZLB
     *
     * @return the value of ZHNY_NSXQ_TRP.NZLB
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getNzlb() {
        return nzlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSXQ_TRP.NZLB
     *
     * @param nzlb the value for ZHNY_NSXQ_TRP.NZLB
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setNzlb(String nzlb) {
        this.nzlb = nzlb == null ? null : nzlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSXQ_TRP.NZYL
     *
     * @return the value of ZHNY_NSXQ_TRP.NZYL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public Double getNzyl() {
        return nzyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSXQ_TRP.NZYL
     *
     * @param nzyl the value for ZHNY_NSXQ_TRP.NZYL
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setNzyl(Double nzyl) {
        this.nzyl = nzyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSXQ_TRP.NZBZ
     *
     * @return the value of ZHNY_NSXQ_TRP.NZBZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getNzbz() {
        return nzbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSXQ_TRP.NZBZ
     *
     * @param nzbz the value for ZHNY_NSXQ_TRP.NZBZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setNzbz(String nzbz) {
        this.nzbz = nzbz == null ? null : nzbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSXQ_TRP.NZTPDZ
     *
     * @return the value of ZHNY_NSXQ_TRP.NZTPDZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getNztpdz() {
        return nztpdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSXQ_TRP.NZTPDZ
     *
     * @param nztpdz the value for ZHNY_NSXQ_TRP.NZTPDZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setNztpdz(String nztpdz) {
        this.nztpdz = nztpdz == null ? null : nztpdz.trim();
    }
}