package com.clesun.web.skyland.entity;

import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

public class ZhnyNsglXq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.id
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    @ApiModelProperty(value = "主键id")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.NSGL_ID
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    @ApiModelProperty(value = "种植记录id")
    private Integer nsglId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.CZR
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    @ApiModelProperty(value = "操作人")
    private String czr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.CZLX
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    @ApiModelProperty(value = "操作类型")
    private String czlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.CZLB
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String czlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.CZKSSJ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    @ApiModelProperty(value = "操作开始时间")
    private Date czkssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.CZJSSJ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    @ApiModelProperty(value = "操作结束时间")
    private Date czjssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.TPDZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String tpdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.CZBZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    @ApiModelProperty(value = "操作备注")
    private String czbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.BY1
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String by1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.BY2
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String by2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.BY3
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String by3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZHNY_NSGL_XQ.CZRBH
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    private String czrbh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.id
     *
     * @return the value of ZHNY_NSGL_XQ.id
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.id
     *
     * @param id the value for ZHNY_NSGL_XQ.id
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.NSGL_ID
     *
     * @return the value of ZHNY_NSGL_XQ.NSGL_ID
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public Integer getNsglId() {
        return nsglId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.NSGL_ID
     *
     * @param nsglId the value for ZHNY_NSGL_XQ.NSGL_ID
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setNsglId(Integer nsglId) {
        this.nsglId = nsglId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.CZR
     *
     * @return the value of ZHNY_NSGL_XQ.CZR
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getCzr() {
        return czr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.CZR
     *
     * @param czr the value for ZHNY_NSGL_XQ.CZR
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setCzr(String czr) {
        this.czr = czr == null ? null : czr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.CZLX
     *
     * @return the value of ZHNY_NSGL_XQ.CZLX
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getCzlx() {
        return czlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.CZLX
     *
     * @param czlx the value for ZHNY_NSGL_XQ.CZLX
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setCzlx(String czlx) {
        this.czlx = czlx == null ? null : czlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.CZLB
     *
     * @return the value of ZHNY_NSGL_XQ.CZLB
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getCzlb() {
        return czlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.CZLB
     *
     * @param czlb the value for ZHNY_NSGL_XQ.CZLB
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setCzlb(String czlb) {
        this.czlb = czlb == null ? null : czlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.CZKSSJ
     *
     * @return the value of ZHNY_NSGL_XQ.CZKSSJ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public Date getCzkssj() {
        return czkssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.CZKSSJ
     *
     * @param czkssj the value for ZHNY_NSGL_XQ.CZKSSJ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setCzkssj(Date czkssj) {
        this.czkssj = czkssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.CZJSSJ
     *
     * @return the value of ZHNY_NSGL_XQ.CZJSSJ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public Date getCzjssj() {
        return czjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.CZJSSJ
     *
     * @param czjssj the value for ZHNY_NSGL_XQ.CZJSSJ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setCzjssj(Date czjssj) {
        this.czjssj = czjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.TPDZ
     *
     * @return the value of ZHNY_NSGL_XQ.TPDZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getTpdz() {
        return tpdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.TPDZ
     *
     * @param tpdz the value for ZHNY_NSGL_XQ.TPDZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setTpdz(String tpdz) {
        this.tpdz = tpdz == null ? null : tpdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.CZBZ
     *
     * @return the value of ZHNY_NSGL_XQ.CZBZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getCzbz() {
        return czbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.CZBZ
     *
     * @param czbz the value for ZHNY_NSGL_XQ.CZBZ
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setCzbz(String czbz) {
        this.czbz = czbz == null ? null : czbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.BY1
     *
     * @return the value of ZHNY_NSGL_XQ.BY1
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getBy1() {
        return by1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.BY1
     *
     * @param by1 the value for ZHNY_NSGL_XQ.BY1
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setBy1(String by1) {
        this.by1 = by1 == null ? null : by1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.BY2
     *
     * @return the value of ZHNY_NSGL_XQ.BY2
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getBy2() {
        return by2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.BY2
     *
     * @param by2 the value for ZHNY_NSGL_XQ.BY2
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setBy2(String by2) {
        this.by2 = by2 == null ? null : by2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.BY3
     *
     * @return the value of ZHNY_NSGL_XQ.BY3
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getBy3() {
        return by3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.BY3
     *
     * @param by3 the value for ZHNY_NSGL_XQ.BY3
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setBy3(String by3) {
        this.by3 = by3 == null ? null : by3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZHNY_NSGL_XQ.CZRBH
     *
     * @return the value of ZHNY_NSGL_XQ.CZRBH
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getCzrbh() {
        return czrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZHNY_NSGL_XQ.CZRBH
     *
     * @param czrbh the value for ZHNY_NSGL_XQ.CZRBH
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setCzrbh(String czrbh) {
        this.czrbh = czrbh == null ? null : czrbh.trim();
    }
}