package com.clesun.web.skyland.entity;

import java.util.ArrayList;
import java.util.List;

public class ZhnyNsxqTrpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    protected int offset = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public ZhnyNsxqTrpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setOffset(int offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNsxqIdIsNull() {
            addCriterion("NSXQ_ID is null");
            return (Criteria) this;
        }

        public Criteria andNsxqIdIsNotNull() {
            addCriterion("NSXQ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andNsxqIdEqualTo(Integer value) {
            addCriterion("NSXQ_ID =", value, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNsxqIdNotEqualTo(Integer value) {
            addCriterion("NSXQ_ID <>", value, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNsxqIdGreaterThan(Integer value) {
            addCriterion("NSXQ_ID >", value, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNsxqIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("NSXQ_ID >=", value, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNsxqIdLessThan(Integer value) {
            addCriterion("NSXQ_ID <", value, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNsxqIdLessThanOrEqualTo(Integer value) {
            addCriterion("NSXQ_ID <=", value, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNsxqIdIn(List<Integer> values) {
            addCriterion("NSXQ_ID in", values, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNsxqIdNotIn(List<Integer> values) {
            addCriterion("NSXQ_ID not in", values, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNsxqIdBetween(Integer value1, Integer value2) {
            addCriterion("NSXQ_ID between", value1, value2, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNsxqIdNotBetween(Integer value1, Integer value2) {
            addCriterion("NSXQ_ID not between", value1, value2, "nsxqId");
            return (Criteria) this;
        }

        public Criteria andNzmcIsNull() {
            addCriterion("NZMC is null");
            return (Criteria) this;
        }

        public Criteria andNzmcIsNotNull() {
            addCriterion("NZMC is not null");
            return (Criteria) this;
        }

        public Criteria andNzmcEqualTo(String value) {
            addCriterion("NZMC =", value, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcNotEqualTo(String value) {
            addCriterion("NZMC <>", value, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcGreaterThan(String value) {
            addCriterion("NZMC >", value, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcGreaterThanOrEqualTo(String value) {
            addCriterion("NZMC >=", value, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcLessThan(String value) {
            addCriterion("NZMC <", value, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcLessThanOrEqualTo(String value) {
            addCriterion("NZMC <=", value, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcLike(String value) {
            addCriterion("NZMC like", value, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcNotLike(String value) {
            addCriterion("NZMC not like", value, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcIn(List<String> values) {
            addCriterion("NZMC in", values, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcNotIn(List<String> values) {
            addCriterion("NZMC not in", values, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcBetween(String value1, String value2) {
            addCriterion("NZMC between", value1, value2, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzmcNotBetween(String value1, String value2) {
            addCriterion("NZMC not between", value1, value2, "nzmc");
            return (Criteria) this;
        }

        public Criteria andNzlbIsNull() {
            addCriterion("NZLB is null");
            return (Criteria) this;
        }

        public Criteria andNzlbIsNotNull() {
            addCriterion("NZLB is not null");
            return (Criteria) this;
        }

        public Criteria andNzlbEqualTo(String value) {
            addCriterion("NZLB =", value, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbNotEqualTo(String value) {
            addCriterion("NZLB <>", value, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbGreaterThan(String value) {
            addCriterion("NZLB >", value, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbGreaterThanOrEqualTo(String value) {
            addCriterion("NZLB >=", value, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbLessThan(String value) {
            addCriterion("NZLB <", value, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbLessThanOrEqualTo(String value) {
            addCriterion("NZLB <=", value, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbLike(String value) {
            addCriterion("NZLB like", value, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbNotLike(String value) {
            addCriterion("NZLB not like", value, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbIn(List<String> values) {
            addCriterion("NZLB in", values, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbNotIn(List<String> values) {
            addCriterion("NZLB not in", values, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbBetween(String value1, String value2) {
            addCriterion("NZLB between", value1, value2, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzlbNotBetween(String value1, String value2) {
            addCriterion("NZLB not between", value1, value2, "nzlb");
            return (Criteria) this;
        }

        public Criteria andNzylIsNull() {
            addCriterion("NZYL is null");
            return (Criteria) this;
        }

        public Criteria andNzylIsNotNull() {
            addCriterion("NZYL is not null");
            return (Criteria) this;
        }

        public Criteria andNzylEqualTo(Double value) {
            addCriterion("NZYL =", value, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzylNotEqualTo(Double value) {
            addCriterion("NZYL <>", value, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzylGreaterThan(Double value) {
            addCriterion("NZYL >", value, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzylGreaterThanOrEqualTo(Double value) {
            addCriterion("NZYL >=", value, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzylLessThan(Double value) {
            addCriterion("NZYL <", value, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzylLessThanOrEqualTo(Double value) {
            addCriterion("NZYL <=", value, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzylIn(List<Double> values) {
            addCriterion("NZYL in", values, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzylNotIn(List<Double> values) {
            addCriterion("NZYL not in", values, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzylBetween(Double value1, Double value2) {
            addCriterion("NZYL between", value1, value2, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzylNotBetween(Double value1, Double value2) {
            addCriterion("NZYL not between", value1, value2, "nzyl");
            return (Criteria) this;
        }

        public Criteria andNzbzIsNull() {
            addCriterion("NZBZ is null");
            return (Criteria) this;
        }

        public Criteria andNzbzIsNotNull() {
            addCriterion("NZBZ is not null");
            return (Criteria) this;
        }

        public Criteria andNzbzEqualTo(String value) {
            addCriterion("NZBZ =", value, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzNotEqualTo(String value) {
            addCriterion("NZBZ <>", value, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzGreaterThan(String value) {
            addCriterion("NZBZ >", value, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzGreaterThanOrEqualTo(String value) {
            addCriterion("NZBZ >=", value, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzLessThan(String value) {
            addCriterion("NZBZ <", value, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzLessThanOrEqualTo(String value) {
            addCriterion("NZBZ <=", value, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzLike(String value) {
            addCriterion("NZBZ like", value, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzNotLike(String value) {
            addCriterion("NZBZ not like", value, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzIn(List<String> values) {
            addCriterion("NZBZ in", values, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzNotIn(List<String> values) {
            addCriterion("NZBZ not in", values, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzBetween(String value1, String value2) {
            addCriterion("NZBZ between", value1, value2, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNzbzNotBetween(String value1, String value2) {
            addCriterion("NZBZ not between", value1, value2, "nzbz");
            return (Criteria) this;
        }

        public Criteria andNztpdzIsNull() {
            addCriterion("NZTPDZ is null");
            return (Criteria) this;
        }

        public Criteria andNztpdzIsNotNull() {
            addCriterion("NZTPDZ is not null");
            return (Criteria) this;
        }

        public Criteria andNztpdzEqualTo(String value) {
            addCriterion("NZTPDZ =", value, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzNotEqualTo(String value) {
            addCriterion("NZTPDZ <>", value, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzGreaterThan(String value) {
            addCriterion("NZTPDZ >", value, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzGreaterThanOrEqualTo(String value) {
            addCriterion("NZTPDZ >=", value, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzLessThan(String value) {
            addCriterion("NZTPDZ <", value, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzLessThanOrEqualTo(String value) {
            addCriterion("NZTPDZ <=", value, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzLike(String value) {
            addCriterion("NZTPDZ like", value, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzNotLike(String value) {
            addCriterion("NZTPDZ not like", value, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzIn(List<String> values) {
            addCriterion("NZTPDZ in", values, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzNotIn(List<String> values) {
            addCriterion("NZTPDZ not in", values, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzBetween(String value1, String value2) {
            addCriterion("NZTPDZ between", value1, value2, "nztpdz");
            return (Criteria) this;
        }

        public Criteria andNztpdzNotBetween(String value1, String value2) {
            addCriterion("NZTPDZ not between", value1, value2, "nztpdz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 21 10:33:42 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZHNY_NSXQ_TRP
     *
     * @mbggenerated Mon Jan 21 10:33:42 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}